project:
  type: website
  output-dir: docs

website:
  title: "R Project Sprint 2023"
  navbar:
    left: 
      - href: code-of-conduct.qmd
        text: Code of Conduct
      - href: participants.qmd
        text: Participants
    right:
      - icon: mastodon
        href: https://mastodon.cloud/tags/RSprint2023
      - icon: twitter
        href: https://twitter.com/hashtag/RSprint2023?src=hashtag_click
      - icon: github
        href: https://github.com/r-project-sprint-2023
  page-navigation: true
  favicon: media/favicon.png
  twitter-card:
    description: A 3-day meeting of R developers to work collaboratively on R core development, hosted at the University of Warwick, August 30 – September 1
  site-url: https://contributor.r-project.org/r-project-sprint-2023

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

